### ISSUE TITLE
Final assembly

### ISSUE THREAD

**Issue by ssasmi** [Ureimu/electron-phaser3-webpack-ts-template#3]
Hello. Please help me. 
After the final build using "package:forge" or "make:forge" should get minified bundles. But in the created directory out\ball-win32-x64\resources\app, all files are in their original form, not minified.
Maybe I'm making the final build incorrectly? 
![1](https://user-images.githubusercontent.com/4318849/177035522-75aa2e34-87ec-414b-b90c-e29192c2a179.png)
![2](https://user-images.githubusercontent.com/4318849/177035523-9f88737e-c0fa-47cb-a0ba-0e02bddc472d.png)

**Comment by Ureimu** [comment]
Sorry for slowly responce, but I didn't find a good way to solve this.
For now, I just manually add all the folder that is not needed to forge-packagerConfig-ignore option in package.json.
Here is an example, maybe it'll help you.
```json
    "config": {
        "forge": {
            "packagerConfig": {
                "ignore": [
                    "profile",
                    "replay",
                    "src",
                    "test",
                    "node_modules",
                    "typeTrace",
                    ".history",
                    "build"
                ]
            }
        }
    },
```

**Comment by ssasmi** [comment]
Thanks. This will help.
